
version: 2.1

orbs:
  newman: postman/newman@0.0.2

jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: https://api.getpostman.com/collections/14272639-1946af36-1f20-485e-bff5-eacbb7c92768?apikey=PMAK-6165f8ac2943cb0035f8e6a1-ff159ed8822a3a3898fe6b7034dca3672f 
          environment: https://api.getpostman.com/environments/ef7b24a6-714d-4aad-b533-2062913a05db?apikey=PMAK-6165f8ac2943cb0035f8e6a1-ff159ed8822a3a3898fe6b7034dca3672f 

workflows:
  example-workflow:
    jobs:
      - newman-collection-run